apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: Dockerfile.prod:imanzi
          ports:
            - containerPort: 8005
          env:
            - name: NODE_ENV
              value: production
          command: ["pm2-runtime", "start", "npm", "--", "start", "-i", "max"]