# Base image
FROM node:lts-alpine AS base
WORKDIR /app
COPY package.json ./
RUN npm install
# Install pm2 globally
RUN npm install -g pm2

# Development image
FROM base AS dev
ENV NODE_ENV=development
COPY . .
CMD ["npm", "run", "dev"]

# Production image
FROM base AS prod
# Build TypeScript code
RUN npm run build
ENV NODE_ENV=production
# ENV HOST=app:8005
COPY src .
CMD ["pm2-runtime", "start", "npm", "--", "start", "-i", "max"]